import os
import sys
import subprocess
import asyncio
import requests
from dotenv import load_dotenv
from thenvoi import Agent
from thenvoi.adapters import OpenAIAdapter
from thenvoi.config import load_agent_config

# Automated Tool for the Mergemaster to push code via GitHub API
def deploy_generated_code(project_id: str) -> str:
    """
    Creates a new GitHub repository dynamically and pushes the generated code.
    """
    github_token = os.getenv("GITHUB_TOKEN")
    github_org_or_user = os.getenv("GITHUB_USERNAME")
    
    # Path where the specific project's code was generated by the Coder agents
    project_folder = os.path.join(os.getcwd(), "generated-projects", project_id)
    
    if not os.path.exists(project_folder):
        return f"Error: Project folder {project_folder} does not exist."

    # Use GitHub API to create a brand new repository
    api_url = "https://api.github.com/user/repos"
    headers = {
        "Authorization": f"token {github_token}",
        "Accept": "application/vnd.github.v3+json"
    }
    repo_data = {
        "name": project_id,
        "description": f"AI Generated Application for {project_id}",
        "private": False,
        "auto_init": False
    }
    
    try:
        response = requests.post(api_url, headers=headers, json=repo_data)
        # 201 means Created successfully. 422 means repo already exists (which is fine for updates)
        if response.status_code not in [201, 422]:
            return f"Failed to create GitHub repository: {response.json().get('message')}"
    except Exception as e:
        return f"GitHub API communication error: {str(e)}"

    # Use local git commands to push the code to the newly created repository
    remote_url = f"https://{github_org_or_user}:{github_token}@github.com/{github_org_or_user}/{project_id}.git"
    
    commands = [
        f"cd {project_folder} && git init",
        f"cd {project_folder} && git checkout -b main",
        f"cd {project_folder} && git add .",
        f'cd {project_folder} && git commit -m "AI Builder Automated Commit"',
        f"cd {project_folder} && git remote remove origin || true", # Prevent duplicate remote errors
        f"cd {project_folder} && git remote add origin {remote_url}",
        f"cd {project_folder} && git push -u origin main --force" # Force push ensures clean builds
    ]
    
    try:
        full_command = " && ".join(commands)
        subprocess.run(full_command, shell=True, check=True, capture_output=True, text=True)
        return f"Successfully pushed {project_id} to GitHub. Deployment triggered at {remote_url}"
    except subprocess.CalledProcessError as e:
        return f"Git Push Execution Error: {e.stderr}"

async def main():
    load_dotenv()

    custom_prompt = """
    You are the Mergemaster. When the Reviewer approves a project:
    1. Extract the Project ID from the incoming context.
    2. Execute the `deploy_generated_code` tool to dynamically provision the repository and push the files.
    3. Confirm to the system that deployment is underway.
    """

    adapter = OpenAIAdapter(
        model="gemini-1.5-flash", # Use the free, high-speed model
        api_key=os.getenv("GOOGLE_AI_STUDIO_API_KEY"),
        base_url="https://generativelanguage.googleapis.com/v1beta/openai/",
        custom_section=custom_prompt
    )

    # adapter = OpenAIAdapter(
    #     model="meta-llama/meta-llama-3-70b-instruct",
    #     api_key=os.getenv("AIML_API_KEY"),
    #     base_url="https://api.aimlapi.com/v1",
    #     custom_section=custom_prompt,
    #     tools=[deploy_generated_code] # Attach the execution tool directly to the agent
    # )

    agent_id, api_key = load_agent_config("mergemaster")
    agent = Agent.create(adapter=adapter, agent_id=agent_id, api_key=api_key)
    
    print("🚀 Mergemaster (With GitHub API Support) is online...")
    await agent.run()

if __name__ == "__main__":
    asyncio.run(main())
    


