import os
import sys
import subprocess
import asyncio
import requests
from dotenv import load_dotenv
from thenvoi import Agent
from thenvoi.adapters import LangGraphAdapter
from thenvoi.config import load_agent_config

# from langchain_openai import ChatOpenAI
from langchain_google_genai import ChatGoogleGenerativeAI

from langgraph.checkpoint.memory import InMemorySaver

def deploy_generated_code(project_id: str) -> str:
    """
    Automates the entire deployment pipeline:
    1. Dynamically creates a new GitHub repository using the GitHub API.
    2. Initializes local git, commits files, and force-pushes to GitHub.
    3. Triggers Vercel via its REST API to import the repo and deploy it live.
    """
    
    # Load required environment variables
    github_token = os.getenv("GITHUB_TOKEN")
    github_user = os.getenv("GITHUB_USERNAME")
    vercel_token = os.getenv("VERCEL_TOKEN")
    
    if not all([github_token, github_user, vercel_token]):
        return "Error: Missing deployment credentials (GITHUB_TOKEN, GITHUB_USERNAME, or VERCEL_TOKEN) in environment."
    
    # Path where the specific project's code was generated by the Coder agents
    project_folder = os.path.join(os.getcwd(), "generated-projects", project_id)
    
    if not os.path.exists(project_folder):
        return f"Error: Project folder {project_folder} does not exist."

    # Create a brand new GitHub Repository dynamically
    github_api_url = "https://api.github.com/user/repos"
    github_headers = {
        "Authorization": f"token {github_token}",
        "Accept": "application/vnd.github.v3+json"
    }
    github_payload = {
        "name": project_id,
        "description": f"AI Generated Application for {project_id}",
        "private": False,
        "auto_init": False
    }
    
    try:
        gh_response = requests.post(github_api_url, headers=github_headers, json=github_payload)
        # 201 = Created, 422 = Already Exists (allows updates/re-runs)
        if gh_response.status_code not in [201, 422]:
            return f"GitHub API Error: Failed to create repository. Message: {gh_response.json().get('message')}"
    except Exception as e:
        return f"GitHub API Communication Failure: {str(e)}"


    # Use local Git commands to push the generated files  
    remote_url = f"https://{github_user}:{github_token}@github.com/{github_user}/{project_id}.git"
    
    git_commands = [
        f"cd {project_folder} && git init",
        f"cd {project_folder} && git checkout -b main",
        f"cd {project_folder} && git add .",
        f'cd {project_folder} && git commit -m "AI Builder Automated Build Allocation"',
        f"cd {project_folder} && git remote remove origin || true",
        f"cd {project_folder} && git remote add origin {remote_url}",
        f"cd {project_folder} && git push -u origin main --force"
    ]
    
    try:
        full_git_command = " && ".join(git_commands)
        subprocess.run(full_git_command, shell=True, check=True, capture_output=True, text=True)
    except subprocess.CalledProcessError as e:
        return f"Git Bash Execution Error: {e.stderr}"

    # Trigger Vercel REST API to link the repository and build
    vercel_project_name = project_id.lower() 
    vercel_api_url = "https://api.vercel.com/v11/projects"
    vercel_headers = {
        "Authorization": f"Bearer {vercel_token}",
        "Content-Type": "application/json"
    }
    vercel_payload = {
        "name": vercel_project_name,
        "framework": "nextjs", 
        "gitRepository": {
            "type": "github",
            "repo": f"{github_user}/{project_id}"
        }
    }
    
    try:
        v_response = requests.post(vercel_api_url, headers=vercel_headers, json=vercel_payload)
        
        # 200 or 201 confirms Vercel successfully bound the repo and initialized the pipeline
        if v_response.status_code in [200, 201]:
            predicted_url = f"https://{vercel_project_name}.vercel.app"
            return f"SUCCESS: {project_id} deployed! Git push complete and Vercel pipeline active. Live URL: {predicted_url}"
        else:
            return f"Partial Success: Pushed to GitHub, but Vercel binding failed: {v_response.json().get('message')}"
            
    except Exception as e:
        return f"Partial Success: Pushed to GitHub, but Vercel API network error occurred: {str(e)}"

async def main():
    # load_dotenv()

    custom_prompt = """
    You are the Mergemaster, the deployment engine of the multi-agent swarm. 
    When the Reviewer passes code changes and gives you the final approval:
    1. Extract the Project ID from the context.
    2. Invoke the `deploy_generated_code` tool immediately to run the GitHub-to-Vercel delivery process.
    3. Report the completion status back to the logging lifecycle.
    """

    adapter = LangGraphAdapter(
        
        # llm=ChatOpenAI(model="gemini-1.5-flash"),
        llm=ChatGoogleGenerativeAI(model="gemini-1.5-flash"),
        
        custom_section=custom_prompt,
        additional_tools=[deploy_generated_code]
    )

    agent_id, api_key = load_agent_config("merge_master")
    agent = Agent.create(adapter=adapter, agent_id=agent_id, api_key=api_key)
    
    print("🚀 Mergemaster (GitHub + Vercel Autonomous Pipeline) is online...")
    await agent.run()

if __name__ == "__main__":
    asyncio.run(main())


